### PR TITLE
Upgrade to PostCSS 8

### PR DESCRIPTION
**Pull request by onigoetz**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [x] yes
- [ ] no

If yes, please describe the breakage.

Upgrade to PostCSS 8

### Please Describe Your Changes

Hello,

This PR upgrades to PostCSS 8,
I had a look at the updated snapshots and they seem fine.

__However__ A change made in PostCSS ( https://github.com/postcss/postcss/commit/0687620df287b205cab72c1e1d58015e576c547e ) Makes the snapshots non-reproducible.

I already open the PR because I'm not sure what course of action we should take as I'm not familiar with AVA.

My ideas would be
- patch the snapshot with a Regex and replace the non-unique IDs with unique ones (although there seems to be no possibility of setting options or serializers for snapshots in AVA)
- mock the ID generator to always return the same ID
- generate temp files, since the IDs are generated only with non named inputs, but that might still be the same problem if the whole file path is added to the output

I'm willing to pass that PR through the finish line but I'm not sure what option to take or if they're even possible

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for working on this 👍 

We can pass the `--u` flag to the test command to update the snapshots. We couldn't patch them manually because they have an accompanying binary file for fidelity and fast comparison. If all of the data minus the IDs are correct, then the snapshots can be safely updated.

**Comment by onigoetz** [comment]
That's the thing, I did update the snapshots.
But since they use a randomly generated IDs, they are different on each run.
That and PostCSS's AST changed (For example adding an "offset" field).

My idea was not to update the snapshots on disk manually, but to pass the result through a filter and then compare it.
I do that in another project where I test a build tool and it displays how long it took to build, I replaced "25ms" with "__ms" since that's not a relevant information for tests

**Comment by shellscape** [comment]
Ah, I see now. Yeah that approach should be fine

**Comment by onigoetz** [comment]
Okay, so I went with a different approach : used `rewiremock` to mock the nanoid module and replace it with an implementation that's not random.

Tests are now running smoothly

**Comment by onigoetz** [comment]
@shellscape Hello, do you need anything from me on this PR ?

**Comment by shellscape** [comment]
Thank you for putting this together, and I'm sorry it took me so very long to get around to merging this. I really appreciate your efforts!

**Comment by onigoetz** [comment]
Thanks for merging! No worries life happens outside GitHub as well :D

**Pull request merged**
