### PR TITLE
Fix Numeric parsing

### PR DESCRIPTION
**Pull request by jonathantneal**
This PR contains:

- [x] bugfix
- [ ] feature
- [x] refactor
- [x] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

---

This changes the parser algorithm for **Numerics** to follow the [CSS Syntax specification](https://drafts.csswg.org/css-syntax/#tokenizer-algorithms) for [Numeric Tokens]((https://drafts.csswg.org/css-syntax/#consume-numeric-token)).

This resolves various issues I am having, where numbers as plain as `32deg` or as modern as `1138--hex` are considered words by this tool.

The code is not lifted from any other tool that I know of, but written by me from my own RegExp implementation of the CSS Syntax, which I have yet to finish or release, and maybe never will.

If fortune allows you to work on OSS, I would greatly appreciate an updated patch or minor release. This PR _does_ remove the internal `parseUnit` and `testUnit` static methods, but those methods were undocumented, and both the `test` and `fromTokens` methods continue to work as expected.

### CODE REVIEW

**Comment by shellscape** [comment]
Good fortune indeed. We've got a work week that allows me time for OSS and I've been catching up.

Given your notes, I'd like to be safe and do a new major version. Do you think that's reasonable, or will that present too large a barrier for upgrading on your end?

**Comment by jonathantneal** [comment]
Yes, I will gladly perform a major update to the affected plugins. Also, I believe your "todos" in the numeric tests can now be added. I only did not want to muddy my PR.

**Comment by jonathantneal** [comment]
Hey, anything I can do to help move this along? If you’ve been busy, that’s understandable, and so this only applies if there is anything I can do in this PR or through other PRs.

**Comment by shellscape** [comment]
We'll get this in today. Check out that CI error in the meantime.

**Comment by shellscape** [comment]
Looks like the version of node that the test container was using didn't like the Ava upgrade. I've updated the container but not sure how long that'll take to update. I'll rerun the tests when that happens.

**Pull request merged**
