### PR TITLE
fix: Function with dot inside name

### PR DESCRIPTION
**Pull request by niksy**
If function contains dot inside it’s name, parser hangs indefinitely (similar to #112). This is possible if [Sass Modules namespace](https://sass-lang.com/documentation/at-rules/use#loading-members) is used.

I don’t know if this should be fixed by default or we should add new option where we allow specific symbols for function names (similar to `interpolation` option).

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

### CODE REVIEW

**Comment by shellscape** [comment]
@niksy this looks good. Please update your snapshots by merging from upstream/master and running `npm run test -- --u`. Once that's done I can merge this.

**Comment by niksy** [comment]
@shellscape OK, done, but now I got a lot of other updated files, is that OK?

**Comment by shellscape** [comment]
Looks like you need to update from upstream/master because 0357c82 was merged before you updated your snapshots

**Comment by niksy** [comment]
@shellscape yup, forgot to install new dependencies, now it looks OK!

**Comment by jonathantneal** [comment]
Fixing the hang is important. Capturing symbols as identifiers would break compatibility with CSS. Is there a way to fix the former without introducing the later?

**Comment by shellscape** [comment]
@jonathantneal any chance you could concoct a test that would show the breakage that @niksy could work with to get an ideal solution?

**Comment by shellscape** [comment]
@jonathantneal checking back in on my last comment. Is that something you're able to do? If not, we can merge this as-is.

**Comment by jonathantneal** [comment]
Patching `Func#fromTokens` or `Func#test` so that it does not swallow up the **full stop** (`.`) opens up other issues, therefore, I think you should merge this as-is.

**Pull request merged**
