### PR TITLE
Use NodeErrorOptions directly from the postcss types

### PR DESCRIPTION
**Pull request by realityking**
A quick follow-up to #132. https://github.com/postcss/postcss/pull/1549 was merged very quickly so now `NodeErrorOptions` can be referenced without a deep import. 

This includes the required upgrade to PostCSS 2.8.9 that includes the above fix.

### CODE REVIEW

**Comment by realityking** [comment]
Tests are failing all over. This must be related to the PostCSS bump.

**Comment by shellscape** [comment]
Looks like snapshots out of date due to the version bump. Some additions and removals from the shape of return objects. You'll have to go over each one individually, but from the few I looked at it looks like it's safe to update the snapshots.

**Comment by realityking** [comment]
@shellscape Can you give me a hint how the snapshots are created? Thanks!

**Comment by shellscape** [comment]
https://github.com/avajs/ava/blob/main/docs/04-snapshot-testing.md

**Comment by realityking** [comment]
Thanks! That worked :)

I had a look through the snapshots and I don't think I can review them. The changes have accumulated over multiple PostCSS versions and I don't know enough about the inner workings of PostCSS.

What I could do, it submit a number of smaller PRs that would have smaller, more isolated changes to the snapshots.

What do you think?

**Comment by shellscape** [comment]
I think you're letting the size of a diff overwhelm you a bit. The differences in the snapshots are almost exclusively around internal `Input` methods `fromOffset` and `isComplete`, which have either been removed by PostCSS in the latest version or replaced with a `Symbol`. Neither of these should have an impact on users, but we can release a major version just to be sure no one is negatively impacted.

**Comment by realityking** [comment]
You're not wrong about the size 😄 But it's compounded by the fact I'm not that familiar with the interface of PostCSS.

I'd be happy to break it into smaller upgrades that I'd be more comfortable reviewing. Let me know if you wanna do that.

**Comment by shellscape** [comment]
I've taken another look over this and I think we're good to go. Dealing with sick kids this week so it may be a delayed release.
thanks!

**Comment by realityking** [comment]
Thanks for taking a look & all the best for your kids 🙂

**Comment by joscha** [comment]
@shellscape any chance we could get a new release with this change? Cheers!

**Pull request merged**
