### PR TITLE
Fix Function RegExp

### LINKED ISSUE #112: postcss-values-parser hangs indefinitely
- Operating System (or Browser): MacOS 10.13.6
- Node Version: 10
- postcss-values-parser Version: 3.2.0

### How Do We Reproduce?

You can reproduce the issue with the following script:
```js
const { parse } = require('postcss-values-parser');

const output = parse('derp-face(#0366d6)');

console.log('Output:', output);
```
How we got into this situation was that we had an undefined (bad) mixin that didn't get resolved and got passed to the values parser. Previously in version 3.1.1 the bad mixin was just ignored, now postcss-values-parser and by relation, webpack hangs indefinitely. We've fixed the bad mixin on our side but some other teams we work with have started seeing the issue. I don't think hanging indefinitely was intended even if this is unexpected css. At a minimum we should probably throw an error if this string is not ok.

Of note: this only breaks if there is a dash in the unresolved mixin.

### Expected Behavior
The previous output of the function was:
```
Root {
  raws: { semicolon: false, after: '' },
  type: 'root',
  nodes:
   [ Func {
       raws: [Object],
       name: 'derp-face',
       type: 'func',
       isColor: false,
       isVar: false,
       nodes: [Array],
       parent: [Circular],
       source: [Object],
       params: '(#0366d6)' } ],
  source:
   { input:
      Input { css: 'derp-face(#0366d6)', hasBOM: false, id: '<input css 1>' },
     start: { line: 1, column: 1 } },
  toString: [Function: bound toString] }
```

### Actual Behavior

The parser hangs indefinitely.

### PR DESCRIPTION
**Pull request by jonathantneal**
This fixes an issue where certain CSS functions can cause the parser to hang indefinitely.

The following [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient) causes the parser to hang indefinitely.

```css
conic-gradient()
```

The 1st commit in this PR addresses the immediate issue with minimal change, where the issue is a lack of support for dashes in function names.

The 2nd commit in this PR addresses the issue with a holistic approach; leveraging [spec compliant](https://drafts.csswg.org/css-syntax/) regular expressions to properly capture [**Number**](https://drafts.csswg.org/css-syntax/#consume-numeric-token) and [**Identifier**](https://drafts.csswg.org/css-syntax/#consume-ident-like-token) tokens. The **Identifier** token represents both the `unit` of a [`Numeric`](https://github.com/shellscape/postcss-values-parser/blob/v3.2.0/docs/Numeric.md) and the `name` of a [`Func`](https://github.com/shellscape/postcss-values-parser/blob/v3.2.0/docs/Func.md).

A side-effect of this approach is that all code related to the [`allFunctions` _whitelist_](https://github.com/shellscape/postcss-values-parser/blob/v3.2.0/lib/nodes/Func.js#L17-L88) becomes obsolete and is removed.

The 3rd commit adds tests for my use-case as well as the example in #112. Therefore, I believe this PR resolves #112.

### CODE REVIEW

**Comment by shellscape** [comment]
I'm not really a fan of this proposed change. The function names that are removed by this change were added so that we can assert that all spec compliant functions are supported. I dislike shifting that to a generic identifier.

**Comment by shellscape** [comment]
Basically I missed a hyphen on a `RegExp`. See https://github.com/shellscape/postcss-values-parser/commit/317357dcb116ddb3c0386c2b27b3584c0b8778a7#diff-a0b9e206953e658d1ff3cdaa45017a6fR126

**Comment by jonathantneal** [comment]
> The function names that are removed by this change were added so that we can assert that all spec compliant functions are supported.

I’ve added those function names to a 4th of tests.

All new spec compliant functions must follow the identifier pattern matched by the regular expression in this PR, because function names are identifiers immediately followed by a left parenthesis. [Citation](https://drafts.csswg.org/css-syntax/#ref-for-next-input-code-point①⑥)

It’s unfortunate to require RegExp tokenization for numbers and identifiers, but PostCSS itself is simply not designed to parse this fidelity of CSS.

**Comment by shellscape** [comment]
I'm just loathe to apply this because I'll have to assume the burden of maintaining a regexp I barely understand, especially so since there's a much simpler fix in the commit I linked to. I always _greatly appreciate your contributions_ but I have to pass on this one. I believe it just adds too much complication that I'm not willing to inherit. This decision will no doubt be contestable, but we'll still be solving the issue at hand.

**Comment by jonathantneal** [comment]
>  I'll have to assume the burden of maintaining a regexp I barely understand

That makes sense to me. I have been considering that as well. You understand the "cost" of fixes, and I’m happy you’ve shared that in a way that I think others can understand. As someone who considers themselves a fellow maintainer, if that’s not too presumptuous, I support your decision.

> This decision will no doubt be contestable

Yea, and that stinks. I imagine referees can nod their heads in solidarity, too. I hope folks remember that these things we make will come and go and come again, but that it’s your ability to create and share and also to _garden_ these works that ultimately helps more folks in the longer run. Seriously, 10 years ago this might have been a contestable PR to a jQuery plugin.

> we'll still be solving the issue at hand.

Thank you for that. Your [patch](https://github.com/shellscape/postcss-values-parser/tree/fix/112/unknown-function-hangs) resolves my issue.

**Comment by shellscape** [comment]
Thanks for that comment. I really do appreciate it.

**Pull request closed without merging**
