### PR TITLE
Add hwb, lab, and lch to functions matching isColor

### PR DESCRIPTION
**Pull request by jonathantneal**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [x] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

---

This PR changes the way the `isColor` property of a `Func` is determined so that it may include [`hwb()`](https://drafts.csswg.org/css-color/#the-hwb-notation), [`lch()`](https://drafts.csswg.org/css-color/#funcdef-lch), and [`lab()`](https://drafts.csswg.org/css-color/#funcdef-lab) notations.

---

_Note: This is not causing me any issues in my current work. It’s just something I noticed while inspecting the code._

_Note: I would expect the `isColor` and `isVar` helper properties to be getters, so that in the event one reassigns a function name, they remain accurate. I am open to adding that in a separate PR if you feel it will add value._

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks! I'll get this merged and released tonight

**Comment by jonathantneal** [comment]
Sweet! I’ll follow along. 👍 Thanks a ton!

**Comment by shellscape** [comment]
Sorry for not getting this published last night. Came down with something and just woke up a bit ago. Looks like I just needed sleep. I have a few tweaks I want to make and then I'll get a new version out.

**Comment by shellscape** [comment]
> Note: I would expect the isColor and isVar helper properties to be getters, so that in the event one reassigns a function name, they remain accurate. I am open to adding that in a separate PR if you feel it will add value.

I'm open to that.

**Pull request merged**
