### PR TITLE
Add TypeScript typings for the package.

### PR DESCRIPTION
**Pull request by nex3**
### This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [x] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

This adds a `.d.ts` file describing the static types of the package's API.

### CODE REVIEW

**Comment by nex3** [comment]
I think the CI failure is due to upstream dependency vulnerabilities that are unrelated to this PR.

**Comment by shellscape** [comment]
@nex3 please merge upstream/master and that should correct CI

**Comment by nex3** [comment]
Done.

**Comment by shellscape** [comment]
thanks!

**Comment by nex3** [comment]
Thanks @shellscape! How soon do you expect this to be released?

**Comment by shellscape** [comment]
I usually do a round of publishing at the beginning of the week and near the end.

**Pull request merged**
