### PR TITLE
Remove dependency on is-url-superb

### PR DESCRIPTION
**Pull request by davilima6**
Addresses the proposed fix in #120 by providing a custom Node `URL`-based implementation for `isUrl`.

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for taking the initiative here. I'm not keen on adding additional code to maintain. I know it's a simple function, but that means it needs tests and such as well. I'd much rather use a package that had its own tests that I didn't have to maintain.

**Comment by davilima6** [comment]
I think adding tests here could be worth the price of avoiding a situation like this from happening again. Only the protocol-relative URLs condition branch needs to be tested. What do you think?

**Comment by davilima6** [comment]
Another issue is that CI fails because package depends on itself (on apparently an outdated version). I see it's imported for performance tests. Would you have any suggestion on how to sort out this one?

**Comment by davilima6** [comment]
Moving PR to draft while we don't have an alternative for 089a196

**Comment by shellscape** [comment]
Closing in favor of #125. As noted on your other PR, I do sincerely and truthfully appreciate the work you put in on this.

**Pull request closed without merging**
